version: '3.8'
services:
  db:
    image: popstar13/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'h'
      MYSQL_DATABASE: 'lena'
    ports:
      - "3307:3306"  # Уникальный порт для теста
    volumes:
      - mysql-data:/var/lib/mysql
  web-server:
    image: popstar13/crudback
    ports:
      - "8081:80"
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - "5001:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
volumes:
  mysql-data:
