version: "3.7"
services:
  web-server:
    image: popstar13/crudback
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - db
      - phpmyadmin
  db:
    image: popstar13/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'gg'
      MYSQL_DATABASE: 'lena'
    ports:
      - "3307:3306"  # Изменили порт, чтобы не конфликтовать с 3306
  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    environment:
      PMA_HOST: 'db'
      PMA_USER: 'root'
      PMA_PASSWORD: 'secret'
    ports:
      - "5001:80"  # Изменили порт на 5001
volumes:
  mysql-data:
